### PR TITLE
Arm docker

### PR DESCRIPTION
**Pull request by grburgess**
sorry.... a typo. it should work now.

### CODE REVIEW

**Comment by grburgess** [comment]
no worries, sorry for the back and forth

**Comment by zevlg** [comment]
Building image for arm64 does not fit into 6h interval reserved for a github job - https://github.com/zevlg/telega.el/actions/runs/4487407116/jobs/7890801945

**Comment by zevlg** [comment]
> yeah, I just saw. I could try and build it locally..

I have m1 mac, what commands should I run to build it locally and push image for arm64 platform?

**Comment by grburgess** [comment]
I was able to build it very quickly and it worked. 

docker build -f etc/Dockerfile .

from the repo root.

**Pull request merged**
