### PR TITLE
Initial support of org-mode links

### LINKED ISSUE #319: Org links aren't rendering
## Telega Setup
*OS*:  macOS 11.5.2
*Emacs*: GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin20.5.0, NS appkit-2022.50 Version 11.4 (Build 20F71))
*Telega*: telega v0.7.80 (TDLib v1.7.8) (telega-server v0.7.13)

## Current Behavior

Org-mode links are not rendered. I have set `telega-chat-input-markups` to `("org" "markdown1" "markdown2")` and can confirm other markup elements (including italics, monospaced, etc.) work fine. It also doesn't work if the text is wrapped with `<org></org>` (e.g. `<org>[[https://github.com/zevlg/telega.el][telega]] is awesome</org>`).

## Steps to Reproduce

1. Open a chat buffer.
2. `C-c C-a` (`telega-chatbuf-attach`)
3. Select `markup`, then `org`.
4. Insert org link, manually or by invoking `org-insert-link`.

### PR DESCRIPTION
**Pull request by SeTSeR**
This support is based on existing telega code. Resolves #319.

### CODE REVIEW

**Comment by zevlg** [comment]
Could you please also add entry for the org links syntax in the “Markup syntax table:” section of the https://github.com/zevlg/telega.el/blob/master/docs/telega-ellit.org

**Comment by SeTSeR** [comment]
> Could you please also add entry for the org links syntax in the “Markup syntax table:” section of the https://github.com/zevlg/telega.el/blob/master/docs/telega-ellit.org

Sure, fixed that, thanks!

**Review by SeTSeR — COMMENTED** [review]
It seems there is some problem with these changes, only links are transformed, removing all previous text.

**Comment by SeTSeR** [comment]
Fixed issue with texts with complex markup and also added tests.

**Comment by zevlg** [comment]
Merged in, thank you for your contribution to `telega.el`!

**Pull request merged**
