### PR TITLE
[WIP]Add dnd dispatch support.

### PR DESCRIPTION
**Pull request by cireu**
深度录屏_选择区域_20190407114235

Allow you to drag file and attach it.

### CODE REVIEW

**Comment by lanact** [comment]
cool ！

**Comment by cireu** [comment]
Now drag an url link will insert it literally at your input position

**Comment by cireu** [comment]
@zevlg Any idea about it?

**Comment by zevlg** [comment]
Great! thanks, I'll do minor modification to your code.  Modifying `dnd-protocol-alist` at `telega-chat.el` load time

**Comment by cireu** [comment]
Thanks for your quick reply

**Comment by cireu** [comment]
Oops, There is still a typo at https://github.com/zevlg/telega.el/blob/telega-with-inserters/telega-chat.el#L2686. Can you help change `telega-dnd-fallback` to `telega-chat-dnd-fallback`? @zevlg

**Comment by zevlg** [comment]
Done, could you please check the modified version

thanks

**Comment by cireu** [comment]
:+1:  Thx

**Pull request merged**
